/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;

//first push - Ravina 17 Sep 2023
public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        AmazonSearch amazon = new AmazonSearch();

        //Todo: call your test case functions one after other here

        //tests.testCase01();
        amazon.testCase01();
        
        //END Tests
        //tests.endTest(); // End your test by clearning connections and closing browser
        amazon.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
