/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //AmazonSearch amazon = new AmazonSearch();
        HyperlinkCount hyperLink = new HyperlinkCount();

        //Todo: call your test case functions one after other here

        //tests.testCase01();
        //amazon.testCase01();
        hyperLink.testCase01();

        //END Tests
        //End your test by clearning connections and closing browser

        //tests.endTest(); 
        //amazon.endTest();
        hyperLink.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
